# "ReplaceMe" will be overwritten by the values in group_config.json

# General
seed: 8888
device: "cuda:4" # <-- change this to the GPU you want to use
debug: False # For logging DEBUG level messages otherwise INFO

# Dir
data_dir: ".."  # <-- change this to the path of the data directory, if you cloned the repo, leave it as "..", the inversion latents will be saved in AnyV2V/
model_name: "i2vgen-xl"
task_name: "Prompt-Based-Editing"
edited_video_name: "ReplaceMe"
output_dir: "${data_dir}/Results/${task_name}/${model_name}/${video_name}/${edited_video_name}/"

# Data
image_size: [512, 512]
video_dir: "${data_dir}/demo"
video_name: "ReplaceMe"
video_path: "ReplaceMe"
video_frames_path: "ReplaceMe"
edited_first_frame_path: "ReplaceMe"
ddim_latents_path: "${data_dir}/inversions/${model_name}/${video_name}/ddim_latents" # Same as inverse_config.output_dir

# Pnp Editing
n_frames: 16
cfg: 9.0
target_fps: 8
editing_prompt: "ReplaceMe"
editing_negative_prompt: "Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
n_steps: 50
ddim_init_latents_t_idx: 1  # 0 for 981, 3 for 921, 9 for 801, 20 for 581 if n_steps=50
ddim_inv_prompt: ""
random_ratio: 0.0

# Pnp config
pnp_f_t: 0.2
pnp_spatial_attn_t: 0.2
pnp_temp_attn_t: 0.5